# sample fedora-messaging consumer configuration file for
# relvalconsumer. Note you must change the UUID here to something
# unique before using this.
#
# This file is in the TOML format.
amqp_url = "amqps://fedora:@rabbitmq.fedoraproject.org/%2Fpublic_pubsub"
callback = "relvalconsumer:RelvalAMIConsumer"

[tls]
ca_cert = "/etc/fedora-messaging/cacert.pem"
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "Fedora release validation event AMI page updater (relvalconsumer)"
app_url = "https://pagure.io/fedora-qa/relvalconsumer"
app_contacts_email = ["qa-devel@lists.fedoraproject.org"]

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false
arguments = {}

# Queue names *must* be in the normal UUID format: run "uuidgen" and use the
# output as your queue name. If your queue is not exclusive, anyone can connect
# and consume from it, causing you to miss messages, so do not share your queue
# name. Any queues that are not auto-deleted on disconnect are garbage-collected
# after approximately one hour.
#
# If you require a stronger guarantee about delivery, please talk to Fedora's
# Infrastructure team.
[queues.00000000-0000-0000-0000-000000000000]
durable = false
auto_delete = true
exclusive = true
arguments = {}

[[bindings]]
queue = "00000000-0000-0000-0000-000000000000"
exchange = "amq.topic"
routing_keys = ["org.fedoraproject.prod.fedimg.image.publish"]
# need this to receive messages from ZMQ->AMQP bridge
[[bindings]]
queue = "00000000-0000-0000-0000-000000000000"
exchange = "zmq.topic"
routing_keys = ["org.fedoraproject.prod.fedimg.image.publish"]

[consumer_config]
# The production instance has this set true. There should be only one
# production instance anywhere in the world at any one time; unless
# you are very sure you are maintaining it, leave this at false.
relvalami_prod = false

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(levelname)s %(name)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.RelvalAMIConsumer]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.twisted]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.pika]
level = "WARNING"
propagate = false
handlers = ["console"]

[log_config.root]
level = "ERROR"
handlers = ["console"]
