[tool.poetry]
name = "assert-info"
version = "0.2.1"
description = "A tool for fixing bare assert statements"
authors = ["Samuel Broster <s.h.broster+gitlab@pm.me>"]
homepage = "https://gitlab.com/broster/assert-info"
repository = "https://gitlab.com/broster/assert-info"
documentation = "https://gitlab.com/broster/assert-info"
readme = "README.rst"

[tool.poetry.dependencies]
python = "~2.7 || ^3.6"
asttokens = "^2.0.4"
docopt = "^0.6.2"
six = "^1.14.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = { version = "^19.10b0", python = "^3.6" }
hypothesis = [
  { version = "^4", python = "~2.7" },
  { version = "^5.11", python = "^3.6" }
]

[tool.poetry.scripts]
assert-info = 'assert_info:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
exclude = '''
(
  /(
      tests/examples
  )/
)
'''