[tool.poetry]
name = "AlekSIS-App-Untis"
version = "2.0a2"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"

description = "AlekSIS (School Information System) — App for Untis import"
authors = ["Dominik George <dominik.george@teckids.org>", "Julian Leucker <leuckeju@katharineum.de>", "Frank Poetzsch-Heffter <p-h@katharineum.de>", "Jonathan Weth <wethjo@katharineum.de>", "Tom Teichler <tom.teichler@teckids.org>", "mirabilos <thorsten.glaser@teckids.org>"]
maintainers = ["Jonathan Weth <wethjo@katharineum.de>", "Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://aleksis.org/"
repository = "https://edugit.org/AlekSIS/official/AlekSIS-App-Untis"
documentation = "https://aleksis.org/AlekSIS/docs/html/"
keywords = ["SIS", "education", "school", "timetable", "plans"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Education",
    "Topic :: Education",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.7"
AlekSIS = "^2.0a2"
AlekSIS-App-Chronos = "^2.0a2"
mysqlclient = "^1.4.6"
tqdm = "^4.44.1"
defusedxml = "^0.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
