[tool.poetry]
name = "quiz-bots"
version = "0.1.5"
description = ""
authors = [
    "Vitaliy Antonov <vitaliyantonoff@gmail.com>"
]

readme = "README.md"

repository = "https://github.com/velivir/quiz-bots"

[tool.poetry.dependencies]
python = "^3.8"
python-telegram-bot = "^12.7"
vk-api = "^11.8.0"
environs = "^7.4.0"
redis = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
add-trailing-comma = "^2.0.1"
autopep8 = "^1.5.2"
docformatter = "^1.3.1"
sphinx = "^3.0.3"
sphinx-autodoc-typehints = "^1.10.3"
sphinxcontrib-mermaid = "^0.4.0"
doc8 = "^0.8.0"
m2r = "^0.2.1"
pre-commit = "^2.3.0"
mypy = "^0.770"
wemake-python-styleguide = "^0.14.0"

[tool.poetry.scripts]
quiz-bots = 'quiz_bots.app:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
