[tool.poetry]
name = "jira-power-tools"
version = "0.2.1"
description = "Tools to improve working with the python jira API."
authors = ["David Bradford <david.bradford@mongodb.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/..."
packages = [
    { include = "jirapt", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
jira = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-black = "^0.3.7"
pytest-cov = "^2.8"
pytest-flake8 = "^1.0"
pytest-mypy = "^0.4"
pytest-pydocstyle = "^2.0"
pytest-sugar = "^0.9.2"

[tool.black]
line-length = 100
target-version = ['py37']
